name: atom_extensions
description: Atom Extensions
repository: https://github.com/pedrolemoz/atom_extensions
version: 1.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  asp: ^1.3.0

dev_dependencies:
  flutterando_analysis: ^0.0.2
  test: ^1.21.0
